#!/bin/sh

vpnc-disconnect
defaultRoute=`cat /tmp/route.prevpnc`
if [ ! -z "$defaultRoute" ]; then
  route delete default
  route add default gw "$defaultRoute"
fi
if [ -f /tmp/resolv.conf.prevpnc ]; then
  cp -f /tmp/resolv.conf.prevpnc /etc/resolv.conf
fi
rm -f /tmp/route.prevpnc /tmp/resolv.conf.prevpnc
