#!/bin/sh

# set -x

cp -f /etc/resolv.conf /tmp/resolv.conf.prevpnc
route -n | awk '$1 == "0.0.0.0" {print $2}' > /tmp/route.prevpnc
vpnc /etc/vpnc/nokia.conf || exit 1
dst=`ifconfig tun0|grep 'inet addr'|sed -e 's/.*inet addr://' -e 's/  P-t-P:.*//'`
route delete default
route add default gw $dst
if [ -f /etc/resolv.conf.nokia ]; then
  cp -f /etc/resolv.conf.nokia /etc/resolv.conf
else
  echo "search europe.nokia.com noe.nokia.com nokia.com ntc.nokia.com nmp.nokia.com europe.nokia.com
nameserver 172.21.141.96
nameserver 172.21.141.108
nameserver 172.27.174.120" > /etc/resolv.conf
fi
