#!/bin/bash

rm -f /tmp/swc.log
exec >/tmp/swc.log 2>&1
set -x

viewerPid=""

getPicOnce() {
    url="http://196.1.123.77:8181/cgi-bin/viewer/video.jpg?resolution=800x600"
    wget -O /tmp/tmp.jpg "$url" >/dev/null 2>&1
    mv /tmp/tmp.jpg /tmp/image.jpg
    [ ! -z "$viewerPid" ] && kill $viewerPid
    sudo fbi -d /dev/fb0 -T 1 -noverbose -a -fitwidth /tmp/image.jpg &
    viewerPid=$!
}

getPicForever() {
    idle=300
    while true; do
        getPicOnce
        sleep $idle
    done
}

getPicForever
