#!/bin/sh
#
# Name		watchmail
# Version	$Id$
#

pause=60
mailbox=${MAILBOX:-/net/marzipan/usr/mail/`id -un`}
mailChecker=checkmail

while true
do
	$mailChecker $mailbox >/dev/null 2>&1
	if [ $? -gt 0 ]
	then
		(
			echo "New mail! "
			grep '^From: ' $mailbox | \
				tail -1 | \
				sed 's/^From:/From/' | \
				tr -d '[<>()]' | \
				tr '[.#_/]' ' '
		) | say >/dev/null 2>&1
		sleep 1
		grep '^Subject: ' $mailbox | tail -1 | say >/dev/null 2>&1
	fi
	sleep $pause
done

#
# End		watchmail
#
