#!/bin/bash

if [ $# != 1 ]; then
	echo "runvnc: Usage: runvnc host_name"
	exit 1
fi

srv=$1

ssh $srv "bash -cl 'vncserver -kill :65; vncserver :65 -geometry 1280x1024'"
exec vncviewer $srv:65 -FullColour
