#!/bin/sh

# This script will run whenever the network location changes.
# See http://forums.applenova.com/archive/index.php/t-17302.html

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin export PATH
set +u
set -x

# User receiving the new configuration
targetUser=polster

# Find my location
getLocation()
{
    location="world"
    ping -t 1 -c 1 172.27.174.120 >/dev/null 2>&1 && location="nokia"
    echo $location
}

# Make sure the target user has Subversion and Mercurial configuration directories
mkdir -p /etc/subversion
mkdir -p /etc/mercurial/hgrc.d

echo "# " `date` >/etc/profile.d/proxy.sh

if [ `getLocation` = "nokia" ]; then

    # Set up the proxy server
    proxyHost=172.16.99.10
    proxyPort=8080

    # Fix host name
    # FIXME: ... but doing so prevents new X connections
    # hostname `nslookup "$DHCP4_IP_ADDRESS" | awk '/name =/ {print $NF}'` \
    #     >/dev/null 2>&1 &

    # Use the Nokia proxy for SVN
    echo '[global]' > /etc/subversion/servers
    echo "http-proxy-host = $proxyHost" >> /etc/subversion/servers
    echo "http-proxy-port = $proxyPort" >> /etc/subversion/servers

    # Use proxy for Mercurial
    echo '[http_proxy]' > /etc/mercurial/hgrc.d/proxy.rc
    echo "host = $proxyHost:$proxyPort" >> /etc/mercurial/hgrc.d/proxy.rc

    # Set proxy environment variables for shells
    # Set proxy environment variables for shells
    echo "http_proxy=http://$proxyHost:$proxyPort/" >>/etc/profile.d/proxy.sh
    echo 'HTTP_PROXY=$http_proxy
https_proxy=$http_proxy
HTTPS_PROXY=$http_proxy
export http_proxy HTTP_PROXY https_proxy HTTPS_PROXY' >>/etc/profile.d/proxy.sh

else

    # No proxy for SVN
    rm -f /etc/subversion/servers
    > /etc/subversion/servers

    # No proxy for Mercurial
    rm -f /etc/mercurial/hgrc.d/proxy.rc
    > /etc/mercurial/hgrc.d/proxy.rc

    # Unset proxy environment variables for shells
    echo 'unset http_proxy HTTP_PROXY https_proxy HTTPS_PROXY' \
        >> /etc/profile.d/proxy.sh

fi

# Fix file permissions and ownerships
chmod a+rx /etc/profile.d/proxy.sh /etc/subversion
chmod a+r /etc/subversion/servers
