#! /bin/sh  

# An SSH_ASKPASS command for MacOS X, with minor modifications to macos-askpass
# by Joseph Mocker, Sun Microsystems.
#
# To use this script:
#     setenv SSH_ASKPASS "ssh-askpass-mac"

TITLE="Enter SSH Password"  
DIALOG="display dialog \"$@\" default answer \"\" with title \"$TITLE\""
DIALOG="$DIALOG with icon 1 with hidden answer"  

result=`osascript -e 'tell application "Finder"' -e "activate"  -e "$DIALOG" -e 'end tell'`  

if [ "$result" = "" ]; then
    exit 1
else
    echo "$result" | sed -e 's/^text returned://' -e 's/, button returned:.*$//'
    exit 0
fi  
