#!/bin/sh
# 
# Created by Marco Ziliani (rylos78@gmail.com) on 04/03/2009
#
# This init script is for Debian/Ubuntu based systems
# 
# Script version 1.3
# 04/03/2009 Added "status" option to get daemon status (running or not running)

### BEGIN INIT INFO
# Provides:          pms
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start PS3 Media Server
### END INIT INFO

unset DISPLAY

# Defaults (EDIT the PMS_HOME variable to the path of your PS3 Media Server, default: /opt/pms)
# Edit also PMSUSER & PMSGROUP to give the credentials you want PS3MediaServer to start with.
PMSUSER=root
PMSGROUP=root
JAVA=`which java`
PMS_HOME=/opt/pms
PMS_JAR="$PMS_HOME/pms.jar"
JAVA_OPTS="-Xmx768M -Djava.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -jar $PMS_JAR $@"

PIDDIR="$PMS_HOME"
PMSDPID=$PIDDIR/pms.pid

export PMS_HOME

# Exit if java is not installed
if [ ! -x "$JAVA" ]; then
{
echo "Java isn't installed, to resolve: sudo apt-get install sun-java6-jre"
exit 99
}
fi


# clear conflicting settings from the environment
unset TMPDIR

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting PS3 Media Server"
		# Make sure we have our PIDDIR, even if it's on a tmpfs
		install -o root -g root -m 755 -d $PIDDIR
		
		log_progress_msg "pmsd"
			cd "$PMS_HOME"
			if ! start-stop-daemon --start --chdir "$PMS_HOME" --background --chuid "$PMSUSER:$PMSGROUP" --make-pidfile --pidfile "$PMSDPID" --quiet --exec "$JAVA" -- $JAVA_OPTS; then
				log_end_msg 1
				exit 1
			fi	
		log_end_msg 0
		;;
	stop)
		log_daemon_msg "Stopping PS3 Media Server"
		log_progress_msg "pmsd"

		start-stop-daemon --stop --quiet --pidfile $PMSDPID
		# Wait a little and remove stale PID file
		sleep 1
		if [ -f $PMSDPID ] > /dev/null
		then
			# Stale PID file, remove it
			rm -f $PMSDPID
		fi

		log_end_msg 0

		;;
	status)
		status="0"
		status_of_proc -p $PMSDPID $JAVA PS3MediaServer || status=$?
		exit $status
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
 	*)
		echo "Usage: /etc/init.d/PS3MediaServer {start|stop|restart|status}"
		exit 1
		;;
esac

exit 0
